name: otomatik_api_akakce

on:
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: main

    # Setup Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Install Python dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install psycopg2-binary requests python-dotenv

    # Run the Python script
    - name: Run otomatik_api_akakce.py
      env:
        PG_DB_USER: ${{ secrets.PG_DB_USER }}
        PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
        PG_HOST: ${{ secrets.PG_HOST }}
        PG_PORT: ${{ secrets.PG_PORT }}
        PG_NAME: ${{ secrets.PG_NAME }}
        PG_VIEW_NAME: ${{ secrets.PG_VIEW_NAME }}
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      run: |
        python ./tests/otomatik_api_akakce.py
